version: '3'

services:
  mkdocs:
    image: "aisuhua/mkdocs:${VERSION:-latest}"
    container_name: docs
    restart: always
    user: "${USERID:-0}:${GID:-0}"
    ports:
      - 8000:8000
    volumes: 
      - .:/docs
