site_name: 望春天

# Site_description
site_author: aisuhua
site_url: https://aisuhua.github.io

# Repository
repo_name: aisuhua/aisuhua.github.io
repo_url: https://github.com/aisuhua/aisuhua.github.io
edit_uri: edit/main/docs/

# Copyright
copyright: <a href="https://github.com/aisuhua">© 2023 aisuhua</a>

# Configuration
theme:
  name: material
  language: zh
  custom_dir: overrides
  # logo: images/desk.png
  favicon: img/favicon.ico
  palette:
    - primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font: false
  icon:
    logo: material/bookmark
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - content.code.copy
    - navigation.footer
    - navigation.tabs
    - content.action.edit
    - announce.dismiss
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.magiclink

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      locale: zh
      type: date
      enable_creation_date: true
  - git-authors:
      show_email_address: false
  - glightbox

extra_css:
  - assets/stylesheets/font.css
  - assets/stylesheets/style.css
 
nav:
  - 首页: index.md
  - 技术:
    - Mirror: mirror.md
    - Docker:
      - Docker: docker/index.md
      - 安装: docker/install.md
    - Podman:
      - Podman: podman/index.md
    - Git:
      - Git: git/index.md
    - Linux:
      - Linux: linux/index.md
      - SSH: linux/ssh.md
      - Network: linux/network.md
      - LVM: linux/lvm.md
      - Kylin: linux/kylin.md
      - Alpine: linux/alpine/index.md
      - FTP: linux/ftp.md
      - ISO: linux/iso.md
      - PDF: linux/pdf.md
      - 概念理解: linux/concepts.md
    - Kubenetes:
      - minikube: kubenetes/minikube.md
    - SSL:
      - 导入证书: ssl/import.md
    - CoreDNS: 
      - CoreDNS: coredns/index.md
      - 安装: coredns/install.md
      - 客户端配置: coredns/client.md
    - OpenShift:
      - OpenShift: openshift/index.md
      - 安装: 
          - 安装: openshift/install/index.md
          - 准备安装介质: openshift/install/download.md
          - 添加域名解析: openshift/install/dns.md
          - 配置负载均衡: openshift/install/lb.md
      - 初始化: openshift/init.md
      - 审计日志: openshift/audit.md
      - 常见问题: openshift/faq.md
    - Windows:
      - 工具: windows/tools.md
      - WSL: windows/wsl.md
    - MySQL:
      - 修改字符集为 utf8mb4: mysql/utf8mb4.md 
    - CSS:
      - CSS: css/index.md 
    - Vmware:
      - 常见问题: vmware/faq.md 
    - 安全:
      - 安全: security/index.md
    - 电子书: book.md
