site_name: 望春天

# Site_description
site_author: aisuhua
site_url: https://aisuhua.github.io

# Repository
repo_name: aisuhua/aisuhua.github.io
repo_url: https://github.com/aisuhua/aisuhua.github.io
edit_uri: edit/main/docs/

# Copyright
copyright: <a href="https://github.com/aisuhua">© 2023 aisuhua</a>

# Configuration
theme:
  name: material
  language: zh
  custom_dir: overrides
  # logo: images/desk.png
  favicon: img/favicon.ico
  palette:
    - primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font: false
  icon:
    logo: material/bookmark
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - content.code.copy
    - navigation.footer
      #- navigation.tabs
    - content.action.edit
    - announce.dismiss
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - emoji.twemoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.magiclink

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      locale: zh
      type: date
      enable_creation_date: true
  - git-authors:
      show_email_address: false
  - glightbox
  - with-pdf
  
extra_css:
  - assets/stylesheets/font.css
  - assets/stylesheets/style.css
 
