name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: aisuhua/mkdocs:latest
      volumes:
        - ./:/src
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: mkdocs build --clean

  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
