# https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
            image: aisuhua/mkdocs:latest
            options: -u $(id -u) -v ${{ github.workspace }}:/src -w /src
            run: |
              mkdocs build --clean
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
